# ─────────────────────────────────────────────────────────────
#  API Gateway - punto de entrada unico de EcoMarket
# ─────────────────────────────────────────────────────────────
spring.application.name=api-gateway
server.port=8080

# Direcciones internas de los microservicios (externalizadas por entorno)
gateway.catalogo-url=${CATALOGO_URL:http://localhost:8081}
gateway.carrito-url=${CARRITO_URL:http://localhost:8082}
