# ─────────────────────────────────────────────────────────────
#  API Gateway - punto de entrada unico de EcoMarket (puerto 8085)
# ─────────────────────────────────────────────────────────────
spring.application.name=api-gateway
server.port=8085

# Direcciones internas de los microservicios (externalizadas por entorno)
gateway.auth-url=${AUTH_URL:http://localhost:8086}
gateway.carrito-url=${CARRITO_URL:http://localhost:8087}
gateway.catalogo-url=${CATALOGO_URL:http://localhost:8088}
