# ─────────────────────────────────────────────────────────────
#  API Gateway - punto de entrada unico de EcoMarket (puerto 8081)
# ─────────────────────────────────────────────────────────────
spring.application.name=api-gateway
server.port=8081

# Direcciones internas de los microservicios (externalizadas por entorno)
gateway.auth-url=${AUTH_URL:http://localhost:8082}
gateway.carrito-url=${CARRITO_URL:http://localhost:8083}
gateway.catalogo-url=${CATALOGO_URL:http://localhost:8084}
